# Generated by Django 4.2.5 on 2023-10-05 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0002_trait_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trait',
            old_name='pet',
            new_name='pets',
        ),
    ]
